# -*- coding: utf-8 -*-
"""Mall Customers .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLGhxnCWu-FxMPYriD52vZ3ysN0CwFDB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('Mall_Customers.csv')

data.head()

x=data.iloc[:,[3,4]].values

from sklearn.cluster import KMeans

wcss = []

for i in range(2,11):
    Kmeans = KMeans(n_clusters=i,init='k-means++',random_state=42)
    Kmeans.fit(x)
    wcss.append(Kmeans.inertia_)

plt.plot(range(2,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

Kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)

y_means=Kmeans.fit_predict(x)

y_means

plt.scatter(x[y_means==0,0],x[y_means==0,1],s=100,c='red',label='Cluster 1')
plt.scatter(x[y_means==1,0],x[y_means==1,1],s=100,c='blue',label='Cluster 2')
plt.scatter(x[y_means==2,0],x[y_means==2,1],s=100,c='green',label='Cluster 3')
plt.scatter(x[y_means==3,0],x[y_means==3,1],s=100,c='cyan',label='Cluster 4')
plt.scatter(x[y_means==4,0],x[y_means==4,1],s=100,c='magenta',label='Cluster 5')